# Spring Boot Settings
server.port=8080
spring.application.name=TaxiDispatchSystem

# Thymeleaf Settings 
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Firebase Credentials Path
# Hướng dẫn sinh viên: Tải file credential từ Firebase Console lưu vào resource với tên firebase-key.json
firebase.credential.path=classpath:firebase-key.json




# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=marispham1509@gmail.com
spring.mail.password=rxlzqiodwhbffecw
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
